# Generated by Django 5.0 on 2024-02-23 18:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=15)),
                ('target_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=255)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=99)),
                ('update_body_measure', models.BooleanField(default=False)),
                ('update_pref_lifestyle', models.BooleanField(default=False)),
                ('attach_body_img', models.BooleanField(default=False)),
                ('attach_med_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='program_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sport_field', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('target_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=255)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=99)),
                ('current_trainees_count', models.PositiveIntegerField(default=0)),
                ('max_trainees_count', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('number_of_ratings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainees', models.ManyToManyField(blank=True, related_name='trainee_programs', to='account.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_weeks', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_trainees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_plans', to='trainings.program')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_reviews', to='account.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Messaging', 'Messaging'), ('Voice Call', 'Voice Call'), ('Video Call', 'Video Call'), ('In Person', 'In Person')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_packages', to='trainings.session')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('availablity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_avilablity', to='trainings.session')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='trainings.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'groups__name': None}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trainer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('sport_field', models.CharField(blank=True, max_length=255)),
                ('document_files', models.FileField(blank=True, upload_to='certifications/')),
                ('id_card', models.FileField(blank=True, upload_to='id_cards/')),
                ('background_image', models.ImageField(blank=True, upload_to='background_images/')),
                ('number_of_trainees', models.PositiveIntegerField(default=0)),
                ('exp_injuries', models.BooleanField(default=False)),
                ('physical_disabilities', models.BooleanField(default=False)),
                ('experience', models.CharField(blank=True, max_length=5, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('avg_ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('number_of_ratings', models.PositiveIntegerField(default=0)),
                ('trainees', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'trainees'}, related_name='trainees', to='account.trainee')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_session', to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='program',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_programs', to='trainings.trainer'),
        ),
        migrations.CreateModel(
            name='Transformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_picture', models.ImageField(upload_to='transformations_pictures/')),
                ('after_picture', models.ImageField(upload_to='transformations_pictures/')),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_transformations', to='trainings.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='workout_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sport_field', models.CharField(blank=True, max_length=255)),
                ('target_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=255)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=99)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_trainees_count', models.PositiveIntegerField(default=0)),
                ('max_trainees_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_in_minutes', models.PositiveIntegerField(default=0)),
                ('avg_ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('number_of_ratings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainees', models.ManyToManyField(blank=True, related_name='trainee_workouts', to='account.trainee')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_workouts', to='trainings.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_files', models.PositiveIntegerField(default=0)),
                ('file_or_video', models.FileField(blank=True, null=True, upload_to='workout_files/')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_videos_files', to='trainings.workout')),
            ],
        ),
    ]
