# Generated by Django 5.0.1 on 2024-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_trainerprofile_experience_and_more'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cupon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='cupon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='number_of_trainees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='trainees',
            field=models.ManyToManyField(blank=True, related_name='trainee_workouts', to='account.traineeprofile'),
        ),
    ]
