# Generated by Django 5.0 on 2024-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('trainings', '0002_remove_trainer_trainees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainees',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='account.trainee'),
        ),
    ]
