# Generated by Django 5.0 on 2024-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_trainer_trainees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutfile',
            name='number_of_files',
        ),
        migrations.AddField(
            model_name='workout',
            name='number_of_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
