# Generated by Django 5.0 on 2024-02-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_remove_workoutfile_number_of_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='sport_field',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='sport_field',
            new_name='level',
        ),
    ]
