# Generated by Django 5.0 on 2024-02-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_trainer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='is_active',
        ),
    ]
