# Generated by Django 5.0 on 2024-02-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainers_club', to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_branches', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubgallery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_gallery', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_facilities', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to='clubs.owner'),
        ),
        migrations.AddField(
            model_name='plan',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_plans', to='clubs.branch'),
        ),
    ]
