# Generated by Django 5.0.1 on 2024-03-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtrainer',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_trainer', to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainers_club', to='clubs.branchtrainer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_branches', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_contact', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_facilities', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to='clubs.branchmember'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='trainer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_trainer', to='trainings.trainer'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='clubs.membersubscription'),
        ),
        migrations.AddField(
            model_name='newtrainer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_new_trainer', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_subscription', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='newtrainer',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='branch_new_trainer_subscription', to='clubs.subscription'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_subscription', to='clubs.subscription'),
        ),
        migrations.AddField(
            model_name='branchtrainer',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='branch_trainer_subscription', to='clubs.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='clubs.subscription'),
        ),
        migrations.AddField(
            model_name='membersubscription',
            name='subscription_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_membership', to='clubs.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_avilablity', to='clubs.branch'),
        ),
        migrations.AddField(
            model_name='time',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_time', to='clubs.workinghours'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('duration', 'subscription')},
        ),
    ]
