# Generated by Django 5.0.1 on 2024-03-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
    ]
