# Generated by Django 5.0.1 on 2024-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
