from django.urls import path

from .views import (
    AddClubToWishlistView,
    AddTrainerToWishlistView,
    AddWorkoutToWishlistView,
    AvailabilityUpdateView,
    ClientRequestAddView,
    ClientRequestTraineeView,
    ClientRequestUpdateView,
    HomeView,
    PaymentAddView,
    PaymentAndProgramView,
    PaymentAndWorkoutView,
    PaymentUpdateView,
    ProgramDeleteView,
    ProgramPlanAddView,
    ProgramTraineeJoinView,
    ProgramUpdateView,
    ProgramAddView,
    RemoveClubFromWishlistView,
    RemoveProgramFromWishlistView,
    RemoveTrainerFromWishlistView,
    RemoveWorkoutFromWishlistView,
    ReviewAddView,
    ReviewUpdateView,
    SearchView,
    TraineeProgramsDetailView,
    ClientRequestTrainerView,
    TraineeUpdateView,
    TrainerProgramsDetailView,
    ProgramsTrainerListView,
    ProgramsTrainersHomeView,
    SessionSettingsUpdateView,
    TimeDeleteView,
    TopRatedTrainersView,
    TraineeDetailView,
    TraineeTrainerDetailView,
    TrainerDetailView,
    TrainerListView,
    TrainerTraineeDetailView,
    TrainerUpdateView,
    TransformationDeleteView,
    TransformationUpdateView,
    TransformationsAddView,
    WorkoutAddView,
    WorkoutDeleteView,
    TrainerWorkoutDetailView,
    WorkoutFileDeleteView,
    WorkoutTraineeJoinView,
    WorkoutUpdateView,
    WorkoutsTrainerListView,
    WorkoutsTrainersHomeView,
)


urlpatterns = [
    path(
        "program-add-wishlist/<int:program_id>/",
        ProgramAddView.as_view(),
        name="program-add-wishlist",
    ),
    path(
        "program-remove-wishlist/<int:program_id>/",
        RemoveProgramFromWishlistView.as_view(),
        name="program-remove-wishlist",
    ),
    path(
        "workout-add-wishlist/<int:workout_id>/",
        AddWorkoutToWishlistView.as_view(),
        name="workout-add-wishlist",
    ),
    path(
        "workout-remove-wishlist/<int:workout_id>/",
        RemoveWorkoutFromWishlistView.as_view(),
        name="workout-remove-wishlist",
    ),
    path(
        "club-add-wishlist/<int:club_id>/",
        AddClubToWishlistView.as_view(),
        name="club-add-wishlist",
    ),
    path(
        "club-remove-wishlist/<int:club_id>/",
        RemoveClubFromWishlistView.as_view(),
        name="club-remove-wishlist",
    ),
    path(
        "trainer-add-wishlist/<int:trainer_id>/",
        AddTrainerToWishlistView.as_view(),
        name="trainer-add-wishlist",
    ),
    path(
        "trainer-remove-wishlist/<int:trainer_id>/",
        RemoveTrainerFromWishlistView.as_view(),
        name="trainer-remove-wishlist",
    ),
    path(
        "trainee-detail/",
        TraineeDetailView.as_view(),
        name="trainee_detail",
    ),
    path(
        "trainer-trainee-detail/<int:trainee_id>/",
        TrainerTraineeDetailView.as_view(),
        name="trainer_trainee_detail",
    ),
    path(
        "top-rated-trainers/",
        TopRatedTrainersView.as_view(),
        name="top-rated-trainers",
    ),
    path(
        "trainers-list/",
        TrainerListView.as_view(),
        name="trainers-list",
    ),
    path(
        "trainee-trainer-detail/<int:user_id>/",
        TraineeTrainerDetailView.as_view(),
        name="trainer_detail",
    ),
    path(
        "payment-and-program/",
        PaymentAndProgramView.as_view(),
        name="payment-and-program",
    ),
    path(
        "payment-and-workout/",
        PaymentAndWorkoutView.as_view(),
        name="payment-and-workout",
    ),
    path(
        "trainer-detail/",
        TrainerDetailView.as_view(),
        name="trainer_detail",
    ),
    path(
        "trainee-update/",
        TraineeUpdateView.as_view(),
        name="trainee_update",
    ),
    path(
        "trainer-update/",
        TrainerUpdateView.as_view(),
        name="trainer_update",
    ),
    path(
        "home/",
        HomeView.as_view(),
        name="home",
    ),
    path(
        "programs-home/",
        ProgramsTrainersHomeView.as_view(),
        name="programs_trainer_list",
    ),
    path(
        "programs-list/",
        ProgramsTrainerListView.as_view(),
        name="programs-list",
    ),
    path(
        "trainee-program/<int:program_id>/",
        TraineeProgramsDetailView.as_view(),
        name="trainee-program-detail",
    ),
    path(
        "trainer-program/<int:program_id>/",
        TrainerProgramsDetailView.as_view(),
        name="trainer-program-detail",
    ),
    path(
        "program-add/",
        ProgramAddView.as_view(),
        name="program-add",
    ),
    path(
        "program-plan-add/<int:program_id>/",
        ProgramPlanAddView.as_view(),
        name="program-plan-add",
    ),
    path(
        "program-join/",
        ProgramTraineeJoinView.as_view(),
        name="program-join",
    ),
    path(
        "program-update/<int:program_id>/",
        ProgramUpdateView.as_view(),
        name="program-update",
    ),
    path(
        "program-delete/<int:program_id>/",
        ProgramDeleteView.as_view(),
        name="program-detail",
    ),
    path(
        "workouts-home/",
        WorkoutsTrainersHomeView.as_view(),
        name="get-programs-trainers",
    ),
    path(
        "workouts-list/",
        WorkoutsTrainerListView.as_view(),
        name="workouts-list",
    ),
    path(
        "workouts/<int:workout_id>/",
        TrainerWorkoutDetailView.as_view(),
        name="workout-detail",
    ),
    path(
        "workout-add/",
        WorkoutAddView.as_view(),
        name="workout-add",
    ),
    path(
        "workout-join/<int:workout_id>/",
        WorkoutTraineeJoinView.as_view(),
        name="workout-join",
    ),
    path(
        "workout-update/<int:workout_id>/",
        WorkoutUpdateView.as_view(),
        name="workout-update",
    ),
    path(
        "workout-delete/<int:workout_id>/",
        WorkoutDeleteView.as_view(),
        name="workout-delete",
    ),
    path(
        "workout-file-delete/<int:workout_file_id>/",
        WorkoutFileDeleteView.as_view(),
        name="workout-file-delete",
    ),
    path(
        "session-settings-update/",
        SessionSettingsUpdateView.as_view(),
        name="session-settings-update",
    ),
    path(
        "availability-update/<int:availability_id>/",
        AvailabilityUpdateView.as_view(),
        name="availability-add",
    ),
    path(
        "time-delete/<int:time_id>/",
        TimeDeleteView.as_view(),
        name="time-delete",
    ),
    path(
        "transformation-add/<int:transformation_id>/",
        TransformationsAddView.as_view(),
        name="transformation_add",
    ),
    path(
        "transformation-update/<int:transformation_id>/",
        TransformationUpdateView.as_view(),
        name="transformation-update",
    ),
    path(
        "transformation-delete/<int:transformation_id>/",
        TransformationDeleteView.as_view(),
        name="transformation-delete",
    ),
    path(
        "payment-add/",
        PaymentAddView.as_view(),
        name="add-payment",
    ),
    path(
        "payment-update/<int:payment_id>/",
        PaymentUpdateView.as_view(),
        name="payment-update",
    ),
    path(
        "client-request-add/",
        ClientRequestAddView.as_view(),
        name="add-client-request",
    ),
    path(
        "client-request-update/<int:client_request_id>/",
        ClientRequestUpdateView.as_view(),
        name="update-client-request",
    ),
    path(
        "client-request-tainee/",
        ClientRequestTraineeView.as_view(),
        name="client-request-trainee",
    ),
    path(
        "client-request-trainer/",
        ClientRequestTrainerView.as_view(),
        name="client-request-trainer",
    ),
    path(
        "Review-add/",
        ReviewAddView.as_view(),
        name="add-review",
    ),
    path(
        "Review-update/<int:review_id>/",
        ReviewUpdateView.as_view(),
        name="update-review",
    ),
    path(
        "search/",
        SearchView.as_view(),
        name="search",
    ),
    # path(
    #     "get_trainer_sessions/<int:pk>/",
    #     get_trainer_sessions,
    #     name="get-trainer-sessions",
    # ),
    # path(
    #     "session_settings/",
    #     add_session_settings,
    #     name="session-settings",
    # ),
]
# path(
#     "add_program/",
#     add_program,
#     name="add-program",
# ),
# path(
#     "edit_program/<int:pk>/",
#     update_program,
#     name="update-program",
# ),
# path(
#     "workouts/",
#     workout_list,
#     name="workout-list",
# ),
# path(
#     "add_workout/",
#     add_workout,
#     name="add-program",
# ),
# path(
#     "update_workout/<int:pk>/",
#     update_workout,
#     name="update-program",
# ),
