# Generated by Django 5.0 on 2024-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traineeprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='exp_injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='physical_disabilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
