# Generated by Django 5.0 on 2024-02-12 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_country_traineeprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
