# Generated by Django 5.0 on 2024-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_trainerprofile_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='certification_files',
            new_name='document_files',
        ),
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='twitter_url',
            new_name='youtube_url',
        ),
    ]
