# Generated by Django 5.0.1 on 2024-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_date_of_birth_dayofyear_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('aerobics', 'Aerobics'), ('archery', 'Archery'), ('badminton', 'Badminton'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('barre', 'Barre'), ('boxing', 'Boxing'), ('bowling', 'Bowling'), ('bodybuilding', 'Bodybuilding'), ('cheerleading', 'Cheerleading'), ('climbing', 'Climbing'), ('cricket', 'Cricket'), ('crossfit', 'Crossfit'), ('cycling', 'Cycling'), ('dance', 'Dance'), ('dodgeball', 'Dodgeball'), ('equestrian', 'Equestrian'), ('fencing', 'Fencing'), ('football', 'Football'), ('golf', 'Golf'), ('gymnastics', 'Gymnastics'), ('handball', 'Handball'), ('hockey', 'Hockey'), ('ice_skating', 'Ice Skating'), ('judo', 'Judo'), ('jui_jitsu', 'Jui Jitsu'), ('karate', 'Karate'), ('krav_maga', 'Krav Maga'), ('lacrosse', 'Lacrosse'), ('martial_arts', 'Martial Arts'), ('mma', 'MMA'), ('muay_thai', 'Muay Thai'), ('other', 'Other'), ('pilates', 'Pilates'), ('powerlifting', 'Powerlifting'), ('rowing', 'Rowing'), ('rugby', 'Rugby'), ('sailing', 'Sailing'), ('skateboarding', 'Skateboarding'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('soccer', 'Soccer'), ('softball', 'Softball'), ('spinning', 'Spinning'), ('strongman', 'Strongman'), ('swimming', 'Swimming'), ('table_tennis', 'Table Tennis'), ('taekwondo', 'Taekwondo'), ('tennis', 'Tennis'), ('track_and_field', 'Track and Field'), ('ultimate_frisbee', 'Ultimate Frisbee'), ('volleyball', 'Volleyball'), ('water_polo', 'Water Polo'), ('weight_lifting', 'Weight Lifting'), ('wrestling', 'Wrestling'), ('yoga', 'Yoga'), ('zumba', 'Zumba')], max_length=255),
        ),
    ]
