# Generated by Django 5.0.1 on 2024-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_trainerprofile_slug_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
