# Generated by Django 5.0.1 on 2024-02-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_trainerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='number_of_trainees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
