# Generated by Django 5.0.1 on 2024-02-06 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_traineeprofile_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'trainers'}, related_name='trainees', to=settings.AUTH_USER_MODEL),
        ),
    ]
