# Generated by Django 5.0.1 on 2024-02-06 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_traineeprofile_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': ''}, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
