# Generated by Django 5.0.1 on 2024-02-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_traineeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='trainees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'trainees'}, related_name='trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': ''}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
