# Generated by Django 5.0.1 on 2024-02-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_trainerprofile_trainees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name': None}, on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': None}, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': None}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
