from django.urls import path

from .views import (
    TrainerProfileDetail,
    TrainerProfileList,
    add_program,
    add_workout,
    get_programs_trainers,
    get_trainer_sessions,
    get_workouts_trainers,
    home,
    add_session_settings,
    program_detail,
    program_list,
    top_rated_trainers,
    update_program,
    update_workout,
    workout_detail,
    workout_list,
)


urlpatterns = [
    path(
        "trainer_profiles/",
        TrainerProfileList,
        name="trainer_profile_list",
    ),
    path(
        "trainer_profiles/<int:pk>/",
        TrainerProfileDetail,
        name="trainer_profile_detail",
    ),
    path(
        "programs/",
        program_list,
        name="program-list",
    ),
    path(
        "programs/<int:pk>/",
        program_detail,
        name="program-detail",
    ),
    path(
        "add_program/",
        add_program,
        name="add-program",
    ),
    path(
        "edit_program/<int:pk>/",
        update_program,
        name="update-program",
    ),
    path(
        "workouts/",
        workout_list,
        name="workout-list",
    ),
    path(
        "workouts/<int:pk>/",
        workout_detail,
        name="workout-detail",
    ),
    path(
        "add_workout/",
        add_workout,
        name="add-program",
    ),
    path(
        "update_workout/<int:pk>/",
        update_workout,
        name="update-program",
    ),
    path(
        "home/",
        home,
        name="home",
    ),
    path(
        "top_rated_trainers/",
        top_rated_trainers,
        name="top-rated-trainers",
    ),
    path(
        "programs_trainers/",
        get_programs_trainers,
        name="get-programs-trainers",
    ),
    path(
        "workouts_trainers/",
        get_workouts_trainers,
        name="get-programs-trainers",
    ),
    path(
        "get_trainer_sessions/<int:pk>/",
        get_trainer_sessions,
        name="get-trainer-sessions",
    ),
    path(
        "session_settings/",
        add_session_settings,
        name="session-settings",
    ),
]
