from django.urls import path

from clubs.serializers import MemberSubscriptionUpdateSerializer
from .views import (
    AttendanceUpdateView,
    BranchDeleteView,
    BranchDetailView,
    BranchGalleriesView,
    BranchGalleryAddView,
    BranchGalleryDeleteView,
    BranchListView,
    BranchLoginView,
    BranchMemberDeleteView,
    BranchMemberJoinView,
    MemberSubscriptionUpdateView,
    TimeDeleteView,
    TraineeBranchMemberUpdateView,
    BranchMembersCountView,
    BranchMembersView,
    BranchRegisterView,
    BranchReviewsView,
    BranchSubscriptionAddView,
    BranchSubscriptionDeleteView,
    BranchSubscriptionPlanDeleteView,
    BranchSubscriptionUpdateView,
    BranchSubscriptionsView,
    BranchTrainersView,
    BranchUpdateView,
    ClubListView,
    ClubLowestToHighestPricebyView,
    ClubNearestToFarthestView,
    ClubSameCountryView,
    MemberSubscriptionDeleteView,
    NewTrainerAddView,
    NewTrainerConvertView,
    NewTrainerDeleteView,
    NewTrainerUpdateView,
    ExistingTrainerAddView,
    PaymentAndBranchMemberAddView,
    ExistingTrainerDeleteView,
    ExistingTrainerUpdateView,
    TraineeBranchDetailView,
    TraineeMemberSubscriptionDeleteView,
)


urlpatterns = [
    path(
        "attendance/<int:attendance_id>/",
        AttendanceUpdateView.as_view(),
        name="attendance_update",
    ),
    path(
        "branch-register/",
        BranchRegisterView.as_view(),
        name="branch_register",
    ),
    path(
        "branch-login/",
        BranchLoginView.as_view(),
        name="branch_login",
    ),
    path(
        "branch-update/",
        BranchUpdateView.as_view(),
        name="branch_update",
    ),
    path(
        "branch-delete/",
        BranchDeleteView.as_view(),
        name="branch_delete",
    ),
    path(
        "branch-detail/",
        BranchDetailView.as_view(),
        name="branch_detail",
    ),
    path(
        "club-list/",
        ClubListView.as_view(),
        name="club_list",
    ),
    path(
        "club-best-prices/",
        ClubLowestToHighestPricebyView.as_view(),
        name="club_nearby",
    ),
    path(
        "branch-list/",
        BranchListView.as_view(),
        name="branch_list",
    ),
    path(
        "branch-trainers/",
        BranchTrainersView.as_view(),
        name="branch_trainers",
    ),
    path(
        "exsiting-trainer-add/",
        ExistingTrainerAddView.as_view(),
        name="existing_trainer_add",
    ),
    path(
        "exsiting-trainer-update/<int:branch_trainer_id>/",
        ExistingTrainerUpdateView.as_view(),
        name="existing_trainer_update",
    ),
    path(
        "exsiting-trainer-delete/<int:branch_trainer_id>/",
        ExistingTrainerDeleteView.as_view(),
        name="existing_trainer_delete",
    ),
    path(
        "new-trainer-add/",
        NewTrainerAddView.as_view(),
        name="new_trainer_add",
    ),
    path(
        "payment-branch-member/",
        PaymentAndBranchMemberAddView.as_view(),
        name="payment_branch_member",
    ),
    path(
        "new-trainer-update/<int:new_trainer_id>/",
        NewTrainerUpdateView.as_view(),
        name="new_trainer_update",
    ),
    path(
        "new-trainer-delete/<int:new_trainer_id>/",
        NewTrainerDeleteView.as_view(),
        name="new_trainer_delete",
    ),
    path(
        "new-trainer-convert/<int:new_trainer_id>/",
        NewTrainerConvertView.as_view(),
        name="new_trainer_convert",
    ),
    path(
        "branch-detail/<int:branch_id>/",
        TraineeBranchDetailView.as_view(),
        name="trainee_branch_detail",
    ),
    path(
        "members/",
        BranchMembersView.as_view(),
        name="branch_members",
    ),
    path(
        "member_delete/<int:member_id>/",
        BranchMemberDeleteView.as_view(),
        name="branch_member_delete",
    ),
    path(
        "subscriptions/",
        BranchSubscriptionsView.as_view(),
        name="branch_subscriptions",
    ),
    path(
        "subscription-add/",
        BranchSubscriptionAddView.as_view(),
        name="branch_subscription_add",
    ),
    path(
        "subscription-update/<int:subscription_id>/",
        BranchSubscriptionUpdateView.as_view(),
        name="branch_subscription_update",
    ),
    path(
        "subscription-delete/<int:subscription_id>/",
        BranchSubscriptionDeleteView.as_view(),
        name="branch_subscription_delete",
    ),
    path(
        "subscription-plan-delete/<int:subscription_plan_id>/",
        BranchSubscriptionPlanDeleteView.as_view(),
        name="branch_subscription_plan_delete",
    ),
    path(
        "galleries/",
        BranchGalleriesView.as_view(),
        name="branch_galleries",
    ),
    path(
        "gallery-add/",
        BranchGalleryAddView.as_view(),
        name="add_branch_gallery",
    ),
    path(
        "gallery-delete/<int:gallery_id>/",
        BranchGalleryDeleteView.as_view(),
        name="delete_branch_gallery",
    ),
    path(
        "reviews/",
        BranchReviewsView.as_view(),
        name="branch_reviews",
    ),
    path(
        "branch-memeber-join/",
        BranchMemberJoinView.as_view(),
        name="branch_member_join",
    ),
    path(
        "time-delete/<int:time_id>/",
        TimeDeleteView.as_view(),
        name="time_delete",
    ),
    path(
        "member-subscription-delete/<int:member_subscription_id>/",
        MemberSubscriptionDeleteView.as_view(),
        name="member_subscription_delete",
    ),
    path(
        "member-subscription-update/<int:member_subscription_id>/",
        MemberSubscriptionUpdateView.as_view(),
        name="member_subscription_update",
    ),
    path(
        "branch-nearest-by-location/",
        ClubNearestToFarthestView.as_view(),
        name="branch_nearby",
    ),
    path(
        "trainee-member-subscription-delete/<int:member_subscription_id>/",
        TraineeMemberSubscriptionDeleteView.as_view(),
        name="trainee_member_subscription_delete",
    ),
    path(
        "club-nearby/",
        ClubSameCountryView.as_view(),
        name="club_nearby",
    ),
    path(
        "branch-members-count/",
        BranchMembersCountView.as_view(),
        name="branch_members_count",
    ),
    path(
        "trainee-branch-member-update/<int:member_id>/",
        TraineeBranchMemberUpdateView.as_view(),
        name="trainee_branch_member-update",
    ),
]
