from django.urls import path
from .views import (
    CompleteProfileTraineeView,
    CompleteProfileTrainerView,
    DeleteAccountView,
    ForgetPasswordView,
    LocationView,
    LoginView,
    LogoutAPIView,
    ResetPasswordView,
    RegisterView,
    RegisterView,
    RequestOTPView,
    ResetPasswordView,
    SetNewPasswordView,
    UpdatePreferenceTrainerView,
    UpdatePreferenceTraineeView,
    VerifyOTPView,
)

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "request-otp/",
        RequestOTPView.as_view(),
        name="request_otp",
    ),
    path(
        "verify-otp/",
        VerifyOTPView.as_view(),
        name="verify_otp_view",
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="reset_password_view",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "delete-account/",
        DeleteAccountView.as_view(),
        name="delete_account",
    ),
    path(
        "logout/",
        LogoutAPIView.as_view(),
        name="logout",
    ),
    path(
        "location/",
        LocationView.as_view(),
        name="location",
    ),
    path(
        "complete-profile-trainee/",
        CompleteProfileTraineeView.as_view(),
        name="complete_profile_trainee",
    ),
    path(
        "complete-profile-trainer/",
        CompleteProfileTrainerView.as_view(),
        name="complete_profile_trainer",
    ),

    path(
        "update-preference-trainee/",
        UpdatePreferenceTraineeView.as_view(),
        name="update_preference_trainee",
    ),
    path(
        "update-preference-trainer/",
        UpdatePreferenceTrainerView.as_view(),
        name="update_preference_trainer",
    ),
    path(
        "forget-password/",
        ForgetPasswordView.as_view(),
        name="forget_password",
    ),
    path(
        "set-new-password/",
        SetNewPasswordView.as_view(),
        name="set_new_password",
    ),
]
